### ISSUE TITLE
App doesn’t work anymore

### ISSUE THREAD

**Issue by Msakkos** [tomaszkoperski/com.tech-controllers#1] opened 2022-09-29 20:46 UTC
Emodul changed something in the server. There are schedules missing and all the historical temperature data too (in emodul app). Unfortunately Homey app also can’t connect with the cloud anymore too. Reinstalled app and trying to fetch zones again, but no luck.

**Comment by tomaszkoperski** [comment] 2022-10-05 09:32
@Msakkos it seems to be an issue with emodul.eu API, which started returning HTTP/400 on authorization requests. I've reached out to Tech Controllers support, will post updates as soon as I hear back from them.

**Comment by tomaszkoperski** [comment] 2022-10-06 12:36
Tech Controllers confirmed that this is an issue on their end and they are working on a fix. As soon as the fix is provided, the app should operate normally. I'll keep an eye on this and close the issue as soon as the API is operational again.

**Comment by tomaszkoperski** [comment] 2022-10-06 20:55
@Msakkos it appears that the issue was fixed.

**Closed as completed** 2022-10-06 20:56 UTC
